### ISSUE TITLE
Fix Path delimiters

### ISSUE THREAD

**Issue by alexeifigueroa** [pettenuzzofabio/image-augmentator#2]
maybe use os.path.join to fix reading/writing files in linux
https://github.com/pettenuzzofabio/image-augmentation/blob/992d77a4adb8c84bdedb78b7d1e0972007c08532/utils/file.py#L20

**Comment by alexeifigueroa** [comment]
https://github.com/pettenuzzofabio/image-augmentation/blob/992d77a4adb8c84bdedb78b7d1e0972007c08532/utils/file.py#L20 maybe use os.path.join so that paths work as well on linux

**Comment by pettenuzzofabio** [comment]
thanks, fixed in commit 5115b352f0940ff7c3bad0f064c21acab3ef0d2d
